// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAA-pNtns3jLCySc9glyovMFWOLJBobqU',
    appId: '1:436356278011:web:dd7e517d23217a32c3f25e',
    messagingSenderId: '436356278011',
    projectId: 'elty-app',
    authDomain: 'elty-app.firebaseapp.com',
    storageBucket: 'elty-app.firebasestorage.app',
    measurementId: 'G-G7K7ZYQFSY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9aBzuDEmrFlWx0EaNe6Z_eraJiYb4M8',
    appId: '1:436356278011:ios:d467bb4b11b362dec3f25e',
    messagingSenderId: '436356278011',
    projectId: 'elty-app',
    storageBucket: 'elty-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV9aBzuDEmrFlWx0EaNe6Z_eraJiYb4M8',
    appId: '1:436356278011:ios:d467bb4b11b362dec3f25e',
    messagingSenderId: '436356278011',
    projectId: 'elty-app',
    storageBucket: 'elty-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAA-pNtns3jLCySc9glyovMFWOLJBobqU',
    appId: '1:436356278011:web:2a76dd2d2351f672c3f25e',
    messagingSenderId: '436356278011',
    projectId: 'elty-app',
    authDomain: 'elty-app.firebaseapp.com',
    storageBucket: 'elty-app.firebasestorage.app',
    measurementId: 'G-BHWKQGM3Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRfEsNYvbQRY1oTAkOdROpyDsnbBRjdM',
    appId: '1:436356278011:android:649316cb5f2fa69fc3f25e',
    messagingSenderId: '436356278011',
    projectId: 'elty-app',
    storageBucket: 'elty-app.firebasestorage.app',
  );

}