name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Calendar
  table_calendar: ^3.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # Notifications & Background
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.6.0

  # PDF Generation
  pdf: ^3.10.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.0

  # Local Storage
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

  # Media
  image_picker: ^1.1.2

  # Authentication & Security
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true